name: Lonnie Comics
favicon: null
layout_spectrum: 1
typography_spectrum: 0.57964
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c0bebf'
    - '#5cc7d9'
    - '#fde800'
    - '#5c8d9b'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
