name: Lonnie Comics
favicon: null
layout_spectrum: 0.49469
typography_spectrum: 0.57964
title: Lonnie Comics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fde700'
    - '#70491e'
    - '#000000'
    - '#ee2326'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
